### ISSUE TITLE
Source tarball size increased from 4 KB to 4.6 MB

### ISSUE THREAD

**Issue by breun** [szazeski/checkssl#1]
The source tarball for checkssl 0.2 is about 4 KB, while the source tarball for version 0.3 is about 4.6 MB. It seems this increase was mainly caused by the addition of binaries under [`lambda/testmain`](https://github.com/szazeski/checkssl/tree/main/lambda/testmain). Do these binaries need to be in the repository and release tarball, or have these been added unintentionally maybe? I'm not sure, just thought I'd ask.

**Comment by szazeski** [comment]
Thank you for pointing that out, yes it was a mistake to add to git. I pushed out a 0.3.1 tag but to be honest there aren't many downloads of checkssl, I would be open to moving the release tag 0.3 if that helps you any since functionally they are the same.

**Comment by breun** [comment]
I maintain the checkssl port for MacPorts and MacPorts servers cache the tarballs, which is how I noticed. But I’d say there is no hurry to do another release now if this is fixed for future releases.
