### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x60a8bf

### ISSUE THREAD

**Issue by michelep** [szazeski/checkssl#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x60a8bf]

goroutine 1 [running]:
github.com/szazeski/checkssl/lib/checkssl.CheckServer({0x7fff4e3f77d8, 0x14}, {0xc00002c648, 0xc00002c628, 0x859a00}, 0x0)
	/Users/steve/go/src/github.com/szazeski/checkssl/lib/checkssl/checkssl.go:85 +0x61f
main.main()
	/Users/steve/go/src/github.com/szazeski/checkssl/main.go:31 +0xc5

**Comment by szazeski** [comment]
Thanks for bringing this up, this happens when a HTTPS TLS connection doesn't actually get created and the server returns a regular http response. I just uploaded a new v0.4.4 that should resolve this issue. Thanks!
