### ISSUE TITLE
Bad install oneliner for linux/mac

### ISSUE THREAD

**Issue by Mazwak** [szazeski/checkssl#5]
Hello

I tried the one liner for linux and encountered 2 errors.

First, there is no version in the final asset, and you put one.
`checkssl_0.5.1_$(uname -s)_$(uname -m).tar.gz`
should be
`checkssl_$(uname -s)_$(uname -m).tar.gz`

the second error is strange comes from zsh smart pasting I think, won’t go in details.

You might want to use /usr/local/bin instead of /usr/bin also.

**Comment by szazeski** [comment]
Thanks for putting in an issue for this. The new goreleaser config no longer takes my filename overrides. The readme is now corrected.

**Comment by szazeski** [comment]
#6
