### ISSUE TITLE
Add an -no-header option for -csv

### ISSUE THREAD

**Issue by Mazwak** [szazeski/checkssl#7]
Hello

If I check a lot of sites, with some being down, the command is very long, because it has a fixed timeout and run in serial.

I don’t need parallelisation inside checkssl, I can do it outside easily.

However, it puts an header for each command.

For example:

`parallel -a my_servers.txt -j 16 --timeout 5s 'checkssl -days=30 -csv "{}"' > ssl_test.csv`

I can do

`parallel -a my_servers.txt -j 16 --timeout 5s 'checkssl -days=30 -csv "{}"' | grep -v Target > ssl_test.csv`

But it would be nice to not have a pipe through grep.

a -timeout option would help also, but parallel will still be faster.

**Comment by szazeski** [comment]
`v0.6.0` adds the `-no-header` option and the `-timeout=1` will set the connection timeout to 1 second.

Thanks for creating this. Let me know if this helps.

**Comment by Mazwak** [comment]
Works perfectly.

Many thanks.
